# Puntos de corte de las áreas 

a = input('Poner el area que quieres ver\n')
g = input('Poner el grado que quieres evaluar\n')
g = float(g)

if a == "Comunicacion":
    if g == 2:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 504.228:
            print("Logrado")
        elif x >= 416.965:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 3:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 525.363:
            print("Logrado")
        elif x >= 418.401:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 4:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 591.449:
            print("Logrado")
        elif x >= 436.966:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 5:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 614.552:
            print("Logrado")
        elif x >= 450.671:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 6:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 568.029:
            print("Logrado")
        elif x >= 407.416:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 7:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 611.478:
            print("Logrado")
        elif x >= 464.447:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 8:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 602.044:
            print('Logrado')
        elif x >= 478.855:
            print('Proceso')
        else:
            print('Inicio')
    elif g == 9:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 581.473:
            print("Logrado")
        elif x >= 441.784:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 10:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 541.184:
            print("Logrado")
        elif x >= 442.615:
            print('Proceso')
        else:
            print('Inicio')
    elif g == 11:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 648.806:
            print("Logrado")
        elif x >= 529.055:
            print("Proceso")
        else:
            print("Inicio")
elif a == "Matematica":
    if g == 2:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 539.271:
            print("Logrado")
        elif x >= 417.150:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 3:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 523.887:
            print('Logrado')
        elif x >= 450.719:
            print('Proceso')
        else:
            print('Inicio')
    elif g == 4:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 609.659:
            print("Logrado")
        elif x >= 449.390:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 5:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 582.819:
            print("Logrado")
        elif x >= 475.043:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 6:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 671.041:
            print("Logrado")
        elif x >= 504.713:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 7:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 740.422:
            print("Logrado")
        elif x >= 558.442:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 8:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 648.044:
            print("Logrado")
        elif x >= 460.918:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 9:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 	698.865:
            print("Logrado")
        elif x >= 508.522:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 10:
        if x > 791.324:
            print("Logrado")
        elif x >= 621.279:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 11:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 662.744:
            print("Logrado")
        elif x >= 554.013:
            print("Proceso")
        else:
            print("Inicio")
elif a == "Ciencias":
    if g == 6:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 746.58:
            print("Logrado")
        elif x >= 587.996:
            print("Proceso")
        else:
            print("Inicio")
    elif g == 8:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 673.958:
            print("Logrado")
        elif x >= 497.17:
            print("Proceso")
        else:
            print("Inicio")
else:
    if g == 8:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 596.827:
            print("Logrado")
        elif x >= 487.93:
            print("Proceso")
        else:
            print("Inicio")
    else:
        x = input('Poner valor del puntaje\n')
        x = float(x)
        if x > 592.163:
            print("Logrado")
        elif x >= 439.212:
            print("Proceso")
        else:
            print("Inicio")
